version: 2
jobs:
  dependencies:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Node dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
  linting:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint
          command: yarn lint
  unit_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Jest
          command: yarn test:unit
          environment:
            TZ: Europe/Paris
  end2end_tests_ios:
    macos:
      xcode: "10.1.0"
    working_directory: ~/app

    steps:
      - checkout

      - attach_workspace:
          at: ~/app

      - restore_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      - run:
          name: Pods dependencies
          command: yarn cocoapods:install

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ~/Library/Caches/CocoaPods
            - ios/Pods

      - restore_cache:
          key: brew-v1-ios-{{ arch }}

      - run:
          name: Brew dependencies
          command: |
            brew tap wix/brew
            brew install applesimutils

      - save_cache:
          key: brew-v1-ios-{{ arch }}
          paths:
            - ~/Library/Caches/Homebrew

      - restore_cache:
          key: detox-v1-{{ arch }}

      - run:
          name: Detox framework
          command: |
            yarn global add detox-cli
            detox build-framework-cache

      - save_cache:
          key: detox-v1-{{ arch }}
          paths:
            - ~/Library/Detox/ios

      - run:
          name: Tests
          command: yarn test:end2end:ios:release
          environment:
            RCT_NO_LAUNCH_PACKAGER: 1
  end2end_tests_android:
    macos:
      xcode: "10.1.0"
    working_directory: ~/app

    steps:
      - checkout

      - attach_workspace:
          at: ~/app

      - restore_cache:
          key: brew-v1-android-{{ arch }}

      - run:
          name: Brew dependencies
          command: |
            brew tap caskroom/cask
            brew cask install android-sdk

      - save_cache:
          key: brew-v1-android-{{ arch }}
          paths:
            - ~/Library/Caches/Homebrew

      - run:
          name: SDK licenses
          # Keep "|| true" because yes command handles a 141 exit code
          command: yes | sdkmanager --licenses || true

      - run:
          name: SDK dependencies
          command: sdkmanager "build-tools;28.0.3" "platforms;android-28" "system-images;android-${API_VERSION};google_apis;${ARCH}"
          environment:
            API_VERSION: 19
            ARCH: x86

      - run:
          name: Emulator
          command: echo no | avdmanager create avd --force --name "Nexus_5X_API_${API_VERSION}" --abi "google_apis/${ARCH}" --package "system-images;android-${API_VERSION};google_apis;${ARCH}" --device "Nexus 5X"
          environment:
            API_VERSION: 19
            ARCH: x86

      - restore_cache:
          key: gradle-v1-{{ checksum "android/app/gradle/dependency-locks/debugCompileClasspath.lockfile" }}-{{ arch }}

      - run:
          name: Gradle dependencies
          command: cd android && ./gradlew androidDependencies
          environment:
            ANDROID_HOME: /usr/local/share/android-sdk

      - save_cache:
          key: gradle-v1-{{ checksum "android/app/gradle/dependency-locks/debugCompileClasspath.lockfile" }}-{{ arch }}
          paths:
            - ~/.gradle/caches

      - run:
          name: Tests
          command: |
            alias emulator="cd \"$ANDROID_HOME/tools\" && ./emulator \"$@\""
            yarn test:end2end:android:debug
          environment:
            RCT_NO_LAUNCH_PACKAGER: 1
            ANDROID_HOME: /usr/local/share/android-sdk
workflows:
  version: 2
  tests-build-deploy:
    jobs:
      - dependencies
      # - linting:
      #    requires:
      #      - dependencies
      # - unit_tests:
      #    requires:
      #      - dependencies
      # - end2end_tests_ios:
      #    requires:
      #      - dependencies
      - end2end_tests_android:
         requires:
           - dependencies
